export const APP_TITLE = 'Verde'
export const APP_DESCRIPTION =
  'Your personal garden store where flowers and greenery meet the convenience of ordering'
export const APP_KEYWORDS = [
  APP_TITLE,
  'Garden app',
  'Plant delivery',
  'Flower shop',
  'Online gardening store',
  'Greenery ordering',
  'Blossom marketplace',
  'Landscaping supplies',
  'Garden decor',
  'Botanical shopping',
  'Floral arrangements',
  'Horticulture essentials',
  'Garden accessories',
  'Garden center',
  'Plant store',
  'Floral delivery',
  'Gardeners paradise',
  'Green thumb tools',
  'Landscaping materials',
  'Indoor plants online',
  'Gardening supplies',
  'Outdoor decor shop',
  'Sustainable gardening',
  'Patio garden products',
  'Blooming flowers',
  'Garden ornaments',
  'Home garden essentials',
  'Gardeners marketplace',
  'Landscape design',
  'Roses',
  'Tulips',
  'Orchids',
  'Lilies',
  'Sunflowers',
  'Daisies',
  'Ferns',
  'Lavender',
  'Hydrangeas',
  'Succulents',
  'Palm trees',
  'Bonsai',
  'Cacti',
  'Violets',
  'Peonies',
  'Carnations',
  'Azaleas',
  'Marigolds',
  'Asters',
  'Daffodils',
  'Begonias',
  'Zinnias',
  'Irises',
  'Geraniums'
]
