name: Main branch pull request / push

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate and create pull request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./apps/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test

      - name: Lint project
        run: yarn lint

      - name: Stylelint project
        run: yarn lint:styles